name: folio
description: Live portfolio developed in Flutter 3.0.

# Prevent package from being accidentally published to pub.dev
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Version control for GitHub API
  github: ^9.2.0

  # Web related packages

  flutter_html: ^2.0.0
  url_strategy: ^0.2.0
  universal_html: ^2.0.4

  flutter_swiper_null_safety: ^1.0.0

  # HTTP requests
  http: ^0.13.1

  # Utility packagesSS
  mailto: ^2.0.0
  flip_card: ^0.6.0
  url_launcher: ^6.0.20
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  carousel_slider_plus: ^7.0.0
  # UI/UX enhancements
  animated_text_kit: ^4.2.1
  font_awesome_flutter: ^10.1.0
  firebase_core: ^1.6.0

  # State management
  provider: ^6.0.1

  # Local storage and caching
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Asset management
  assets:
    - assets/
    - assets/photos/
    - assets/work/
    - assets/services/
    - assets/projects/
    - assets/hi.gif
    - data.json

  # Font management
  fonts:
    - family: Agustina
      fonts:
        - asset: fonts/agustina/agustina.otf

    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/montserrat.ttf

    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Light.ttf
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 900
        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 300
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 500
        - asset: fonts/poppins/Poppins-Italic.ttf
          style: italic
